Repository trustbloc/auth, pull requests merged in 2020-11, with the labels that each got.

#62 refactor: use cookies
  cmd/auth-rest/go.sum
  cmd/auth-vue/src/pages/SelectProvider.vue
  go.mod
  go.sum
  pkg/restapi/common/store/cookie/api.go
  pkg/restapi/common/store/cookie/mock.go
  pkg/restapi/common/store/cookie/store.go
  pkg/restapi/operation/models.go
  pkg/restapi/operation/operations.go
  pkg/restapi/operation/operations_test.go
Labels: cla-signed, refactor

#63 chore: missing hydra consent handler
  pkg/restapi/operation/dependencies.go
  pkg/restapi/operation/models.go
  pkg/restapi/operation/operations.go
  pkg/restapi/operation/operations_test.go
  pkg/restapi/operation/transient.go
Labels: cla-signed

#68 feat: mysql storage
  cmd/auth-rest/go.mod
  cmd/auth-rest/go.sum
  cmd/auth-rest/startcmd/start.go
  cmd/auth-rest/startcmd/start_test.go
  cmd/auth-rest/startcmd/storage.go
  pkg/restapi/operation/operations.go
  test/bdd/fixtures/auth-rest/docker-compose.yml
  test/bdd/fixtures/auth-rest/mysql-config/mysql_config.sql
Labels: cla-signed, enhancement

#69 refactor: Add mock bank login button and remove other OIDC provider
  cmd/auth-vue/src/pages/SelectProvider.vue
Labels: cla-signed

#70 fix: serve UI + oidc provider retries
  Makefile
  cmd/auth-rest/startcmd/start.go
  cmd/auth-vue/package-lock.json
  go.mod
  go.sum
  images/auth-rest/Dockerfile
  pkg/restapi/controller_test.go
  pkg/restapi/operation/operations.go
  pkg/restapi/operation/operations_test.go
Labels: bug, cla-signed

#71 fix: typo in oauth2 scopes
  pkg/restapi/operation/operations.go
Labels: cla-signed

#72 fix: add referrer meta
  cmd/auth-vue/public/index.html
Labels: cla-signed

#73 test: store access token in bddtest ctx
  test/bdd/pkg/context/context.go
  test/bdd/pkg/login/mock_wallet.go
  test/bdd/pkg/login/steps.go
Labels: cla-signed

#74 feat: POST /bootstrap
  pkg/restapi/common/hydra/client.go
  pkg/restapi/common/hydra/client_test.go
  pkg/restapi/operation/dependencies.go
  pkg/restapi/operation/models.go
  pkg/restapi/operation/operations.go
  pkg/restapi/operation/operations_test.go
  test/bdd/bddtests_test.go
  test/bdd/features/bootstrap_data.feature
  test/bdd/fixtures/auth-rest/docker-compose.yml
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/bootstrap/steps.go
  test/bdd/pkg/login/mock_wallet.go
  test/bdd/pkg/login/steps.go
Labels: cla-signed, enhancement

#75 feat: GET and POST /secret
  cmd/auth-rest/startcmd/start.go
  cmd/auth-rest/startcmd/start_test.go
  pkg/restapi/operation/models.go
  pkg/restapi/operation/operations.go
  pkg/restapi/operation/operations_test.go
  test/bdd/bddtests_test.go
  test/bdd/features/secrets.feature
  test/bdd/fixtures/auth-rest/docker-compose.yml
  test/bdd/pkg/login/mock_wallet.go
  test/bdd/pkg/secrets/mock_key_server.go
  test/bdd/pkg/secrets/steps.go
Labels: cla-signed, enhancement

#76 refactor: bootstrap data
  cmd/auth-rest/startcmd/start.go
  cmd/auth-rest/startcmd/start_test.go
  pkg/bootstrap/user/userprofile.go
  pkg/bootstrap/user/userprofile_test.go
  pkg/restapi/operation/models.go
  pkg/restapi/operation/operations.go
  pkg/restapi/operation/operations_test.go
  test/bdd/features/secrets.feature
  test/bdd/fixtures/auth-rest/docker-compose.yml
  test/bdd/pkg/bootstrap/steps.go
  test/bdd/pkg/secrets/steps.go
Labels: cla-signed, refactor

#77 chore: #65 configure cookie auth and enc keys
  .gitignore
  cmd/auth-rest/startcmd/start.go
  cmd/auth-rest/startcmd/start_test.go
  scripts/generate_test_keys.sh
  test/bdd/fixtures/auth-rest/docker-compose.yml
Labels: chore, cla-signed

#78 feat: #61 support multiple OIDC providers
  cmd/auth-rest/go.mod
  cmd/auth-rest/startcmd/parameters.go
  cmd/auth-rest/startcmd/start.go
  cmd/auth-rest/startcmd/start_test.go
  pkg/restapi/controller_test.go
  pkg/restapi/operation/dependencies.go
  pkg/restapi/operation/operations.go
  pkg/restapi/operation/operations_test.go
  test/bdd/fixtures/auth-rest/docker-compose.yml
  test/bdd/fixtures/auth-rest/oidc-config/providers.yaml
  test/bdd/pkg/login/steps.go
Labels: cla-signed, enhancement

#79 fix: align provider ID b/w frontend and backend config
  cmd/auth-vue/src/pages/SelectProvider.vue
  test/bdd/fixtures/auth-rest/oidc-config/providers.yaml
  test/bdd/pkg/login/steps.go
Labels: cla-signed

#80 refactor: Fetch Bootstrap Response json key (entries -> data)
  pkg/restapi/operation/models.go
Labels: cla-signed
