Repository trustbloc/auth, pull requests merged in 2020-12, with the labels that each got.

#83 fix: improve hub-auth ui for demo
  cmd/auth-vue/public/index.html
  cmd/auth-vue/src/pages/SelectProvider.vue
  cmd/auth-vue/src/pages/layout/Nav.vue
Labels: cla-signed

#84 docs: add documentation
  README.md
  docs/img/overview.svg
  docs/overview.md
Labels: cla-signed, documentation

#85 chore: prepping for release of 0.1.5
  ci/version_var.sh
  cmd/auth-rest/go.mod
  cmd/auth-rest/go.sum
  cmd/auth-rest/startcmd/start_test.go
  go.mod
  go.sum
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#86 chore: bump version to 0.1.6
  ci/version_var.sh
Labels: chore, cla-signed
