Repository trustbloc/auth, pull requests merged in 2022-04, with the labels that each got.

#182 refactor: rename hub-auth to auth
  .github/workflows/build.yml
  .golangci.yml
  Makefile
  README.md
  ci/version_var.sh
  cmd/auth-rest/go.mod
  cmd/auth-rest/main.go
  cmd/auth-rest/startcmd/parameters.go
  cmd/auth-rest/startcmd/start.go
  cmd/auth-rest/startcmd/start_test.go
  cmd/auth-rest/startcmd/test/data/providers.yaml
  cmd/auth-vue/README.md
  cmd/auth-vue/package-lock.json
  cmd/auth-vue/package.json
  docs/img/overview.svg
  docs/overview.md
  go.mod
  go.sum
  images/auth-rest/Dockerfile
  pkg/bootstrap/user/userprofile.go
  pkg/gnap/accesspolicy/access_policy.go
  pkg/gnap/api/api.go
  pkg/gnap/session/session_manager.go
  pkg/restapi/common/store/cookie/store.go
  pkg/restapi/controller.go
  pkg/restapi/controller_test.go
  pkg/restapi/gnap/operations.go
  pkg/restapi/gnap/operations_test.go
  pkg/restapi/operation/operations.go
  pkg/restapi/operation/operations_test.go
  scripts/check_integration.sh
  scripts/check_unit.sh
  scripts/generate_test_keys.sh
  spi/gnap/clientverifier/httpsig/verifier.go
  spi/gnap/go.mod
  test/bdd/bddtests_test.go
  test/bdd/features/bootstrap_data.feature
  test/bdd/features/login.feature
  test/bdd/features/secrets.feature
  test/bdd/fixtures/auth-rest/.env
  test/bdd/fixtures/auth-rest/docker-compose.yml
  test/bdd/fixtures/auth-rest/hydra-config/thirdparty_hydra_configure.sh
  test/bdd/fixtures/auth-rest/oidc-config/providers.yaml
  test/bdd/go.mod
  test/bdd/pkg/bootstrap/steps.go
  test/bdd/pkg/common/common_steps.go
  test/bdd/pkg/login/mock_wallet.go
  test/bdd/pkg/login/steps.go
  test/bdd/pkg/secrets/mock_key_server.go
  test/bdd/pkg/secrets/steps.go
Labels: cla-signed

#186 feat: upgraded auth-vue to Vue 3, Vite, TailwindCSS v3, etc.
  cmd/auth-vue/.eslintignore
  cmd/auth-vue/.eslintrc.cjs
  cmd/auth-vue/.gitignore
  cmd/auth-vue/.prettierignore
  cmd/auth-vue/.prettierrc
  cmd/auth-vue/README.md
  cmd/auth-vue/babel.config.js
  cmd/auth-vue/index.html
  cmd/auth-vue/package-lock.json
  cmd/auth-vue/package.json
  cmd/auth-vue/postcss.config.js
  cmd/auth-vue/public/favicon.ico
  cmd/auth-vue/public/favicon.png
  cmd/auth-vue/public/index.html
  cmd/auth-vue/src/App.vue
  cmd/auth-vue/src/assets/.gitkeep
  cmd/auth-vue/src/assets/bg-onboarding-sm.svg
  cmd/auth-vue/src/assets/bg-onboarding.svg
  cmd/auth-vue/src/assets/close-icon.svg
  cmd/auth-vue/src/assets/logo.svg
  cmd/auth-vue/src/assets/signup/onboarding-icon-1.svg
  cmd/auth-vue/src/assets/signup/onboarding-icon-2.svg
  cmd/auth-vue/src/assets/signup/onboarding-icon-3.svg
  cmd/auth-vue/src/assets/triangle-exclamation.svg
  cmd/auth-vue/src/components/.gitkeep
  cmd/auth-vue/src/components/TheFooter.vue
  cmd/auth-vue/src/components/TheLocaleSwitcher.vue
  cmd/auth-vue/src/components/TheToastNotification.vue
  cmd/auth-vue/src/components/icons/IconLogo.vue
  cmd/auth-vue/src/components/icons/IconSpinner.vue
  cmd/auth-vue/src/config/supportedLocales.js
  cmd/auth-vue/src/main.js
  cmd/auth-vue/src/mixins/i18n/document.js
  cmd/auth-vue/src/mixins/i18n/getBrowserLocale.js
  cmd/auth-vue/src/mixins/i18n/getStartingLocale.js
  cmd/auth-vue/src/pages/PageNotFound.vue
  cmd/auth-vue/src/pages/SelectProvider.vue
  cmd/auth-vue/src/pages/layout/Footer.vue
  cmd/auth-vue/src/pages/layout/Nav.vue
  cmd/auth-vue/src/pages/layout/img/logo.png
  cmd/auth-vue/src/plugins/breakpoints.js
  cmd/auth-vue/src/plugins/i18n.js
  cmd/auth-vue/src/router/TheRoot.vue
  cmd/auth-vue/src/router/index.js
  cmd/auth-vue/src/router/routes.js
  cmd/auth-vue/src/tailwind.css
  cmd/auth-vue/src/translations/en.json
  cmd/auth-vue/src/translations/fr.json
  cmd/auth-vue/src/views/NotFound.vue
  cmd/auth-vue/src/views/SignIn.vue
  cmd/auth-vue/src/views/SignUp.vue
  cmd/auth-vue/tailwind.config.mjs
  cmd/auth-vue/tailwind.js
  cmd/auth-vue/vite.config.js
  cmd/auth-vue/vue.config.js
Labels: enhancement, cla-signed

#188 feat: added dependabot config file
  .github/dependabot.yml
Labels: type: enhancement, cla-signed

#163 chore: introduce gnap client interface
  .gitignore
  Makefile
  component/gnap/as/client.go
  component/gnap/as/client_test.go
  component/gnap/rs/client.go
  component/gnap/rs/client_test.go
  component/gnap/testdata/scripts/generate_test_keys.sh
  scripts/check_unit.sh
  spi/gnap/api.go
  spi/gnap/go.mod
  spi/gnap/models.go
Labels: cla-signed

#181 feat: AuthHandler performing basic GNAP AS logic
  cmd/auth-rest/go.mod
  cmd/auth-rest/go.sum
  cmd/auth-rest/startcmd/start.go
  component/gnap/as/client_test.go
  component/gnap/rs/client_test.go
  go.mod
  go.sum
  pkg/gnap/accesspolicy/access_policy.go
  pkg/gnap/accesspolicy/access_policy_test.go
  pkg/gnap/api/api.go
  pkg/gnap/authhandler/auth_handler.go
  pkg/gnap/authhandler/auth_handler_test.go
  pkg/gnap/authhandler/helpers.go
  pkg/gnap/helpers.go
  pkg/gnap/interact/redirect/interact.go
  pkg/gnap/session/session_manager.go
  pkg/gnap/session/session_manager_test.go
  pkg/internal/common/mockinteract/interact.go
  pkg/internal/common/mockverifier/verifier.go
  pkg/restapi/controller.go
  pkg/restapi/controller_test.go
  pkg/restapi/gnap/operations.go
  pkg/restapi/gnap/operations_test.go
  spi/gnap/go.mod
  spi/gnap/go.sum
  spi/gnap/models.go
  spi/gnap/parse_test.go
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#194 feat: updated lint target to include frontend
  .github/workflows/build.yml
  cmd/auth-vue/package.json
  cmd/auth-vue/src/App.vue
  cmd/auth-vue/src/components/TheFooter.vue
  cmd/auth-vue/src/components/TheToastNotification.vue
  cmd/auth-vue/src/views/SignIn.vue
  cmd/auth-vue/src/views/SignUp.vue
  cmd/auth-vue/tailwind.config.mjs
  scripts/check_lint.sh
Labels: type: enhancement, cla-signed

#199 test: update cucumber/godog version
  cmd/auth-rest/go.mod
  cmd/auth-rest/go.sum
  go.mod
  go.sum
  test/bdd/bddtests_test.go
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/bootstrap/steps.go
  test/bdd/pkg/common/common_steps.go
  test/bdd/pkg/login/steps.go
  test/bdd/pkg/secrets/steps.go
Labels: cla-signed

#201 test: GNAP flow bdd - initial version
  pkg/gnap/interact/redirect/interact.go
  spi/gnap/clientverifier/httpsig/verifier.go
  test/bdd/bddtests_test.go
  test/bdd/features/gnap.feature
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/gnap/signer.go
  test/bdd/pkg/gnap/steps.go
Labels: cla-signed

#202 feat: Interact handler
  .github/workflows/build.yml
  cmd/auth-rest/startcmd/parameters.go
  cmd/auth-rest/startcmd/start.go
  docs/build.md
  pkg/gnap/interact/redirect/interact.go
  pkg/restapi/gnap/operations.go
  pkg/restapi/gnap/operations_test.go
  scripts/generate_test_keys.sh
  test/bdd/fixtures/auth-rest/docker-compose.yml
  test/bdd/pkg/gnap/steps.go
Labels: cla-signed

#204 feat: session manager using storage api for persistence
  cmd/auth-rest/startcmd/start.go
  pkg/gnap/authhandler/auth_handler.go
  pkg/gnap/authhandler/auth_handler_test.go
  pkg/gnap/session/session_manager.go
  pkg/gnap/session/session_manager_test.go
  pkg/internal/common/mockstorage/storage.go
  pkg/restapi/controller.go
  pkg/restapi/controller_test.go
  pkg/restapi/gnap/operations.go
  pkg/restapi/gnap/operations_test.go
Labels: cla-signed
